/** Production modules exercised against a strict local KV/SQLite adapter.
 * These are Node contract tests, NOT a substitute for mandatory workerd/Vitest.
 * The optional SOURCE_ROOT is only a test-input selector for before/after reproduction.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {fixture} from '../upgrade/helpers.mjs';
const root=path.resolve(process.env.SUBSTRACKER_CONTRACT_SOURCE_ROOT || new URL('../..',import.meta.url).pathname);
const load=p=>import(pathToFileURL(path.join(root,p)));
const inventory=await load('src/data/upgrade-reconcile.js');
const superadmin=await load('src/core/superadmin.js');
const {acceptSubscriptionRecord}=await load('src/data/subscription-workflow.js');
const {getCategories}=await load('src/data/categories.js');
const {getMenuOptions}=await load('src/data/menu-options.js');
const {getAllSubscriptions}=await load('src/data/subscriptions.js');
const {handleApiRequest}=await load('src/api/router.js');
const {generateJWT,verifyJWT}=await load('src/core/auth.js');
const {checkExpiringSubscriptions}=await load('src/services/scheduler.js');
const reminders=await load('src/data/reminders.repo.js');
function fresh(t,options={}) {return fixture({d1:false,rows:[],...options}).then(f=>{t.after(()=>f.close());return f;});}
function freeze(t,iso) {const Original=globalThis.Date;let now=Original.parse(iso);globalThis.Date=class extends Original {constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};t.after(()=>globalThis.Date=Original);return next=>{now=Original.parse(next);};}
function mockChannel(t,{failFirst=false}={}) {const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;const ok=!(failFirst&&calls===1);return new Response(JSON.stringify({ok,result:{message_id:1}}),{status:ok?200:500});};t.after(()=>globalThis.fetch=original);return ()=>calls;}
function config(f,extra={}) {const cfg={ADMIN_USERNAME:'admin',ADMIN_PASSWORD:'ordinary-secret',JWT_SECRET:'local-only-jwt',CREDENTIALS_ENCRYPTION_KEY:'local-only-credential',TIMEZONE:'UTC',NOTIFICATION_HOURS:[],ENABLED_NOTIFIERS:['telegram'],TG_BOT_TOKEN:'local-not-sent',TG_CHAT_ID:'local',...extra};f.values.set('config',JSON.stringify(cfg));return cfg;}
async function seed(f,sub,rule) {f.values.set('sub:'+sub.id,JSON.stringify(sub));f.values.set('sub_index',JSON.stringify([sub.id]));if(rule)await reminders.replaceForSubscription(f.env,sub.id,[reminders.normalizeRule(rule)]);}
async function api(f,method,url,body) {const cfg=JSON.parse(f.values.get('config'));const token=await generateJWT(cfg.ADMIN_USERNAME,cfg.JWT_SECRET);const res=await handleApiRequest(new Request('https://local.invalid'+url,{method,headers:{Cookie:'token='+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),f.env);return {res,body:await res.json()};}
const incoming={name:'Contract Service',account:'test@example.invalid',category:'流媒体',customType:'开会员',subscriptionMode:'reset',startDate:'2030-01-01',expiryDate:'2030-02-01',amount:10,memberLevel:'Pro'};

test('strict adapter reproduces rejected cacheTtl=30, rather than silently accepting it',async t=>{const f=await fresh(t);await assert.rejects(f.env.SUBSCRIPTIONS_KV.get(['config'],{type:'text',cacheTtl:30}),/at least 60/);});
test('production bulk read uses a compatible TTL and preserves all values',async t=>{const f=await fresh(t);f.values.set('one','中文');f.values.set('empty','');const out=await inventory.readKVTexts(f.env.SUBSCRIPTIONS_KV,['one','empty','absent']);assert.deepEqual([...out],[['one','中文'],['empty',''],['absent',null]]);});
test('more than 100 keys are split without omission',async t=>{const f=await fresh(t);const names=Array.from({length:205},(_,i)=>'k'+i);names.forEach(k=>f.values.set(k,k));const out=await inventory.readKVTexts(f.env.SUBSCRIPTIONS_KV,names);assert.equal(out.size,205);assert.equal(f.control.kvOperations,3);});
test('old runtime rejecting array overload falls back to string reads only',async()=>{let strings=0;const kv={async get(k){if(Array.isArray(k))throw new TypeError("Incorrect type for the 'key' parameter: not of type 'string'");strings++;return k+'!';}};assert.deepEqual([...await inventory.readKVTexts(kv,['a','b'])],[['a','a!'],['b','b!']]);assert.equal(strings,2);});
test('permission failures propagate without a misleading single-key fallback',async()=>{let n=0;await assert.rejects(inventory.readKVTexts({async get(){n++;throw new Error('403 denied');}},['x']),/403/);assert.equal(n,1);});
test('partial bulk response is an error, never an empty successful inventory',async()=>{await assert.rejects(inventory.readKVTexts({async get(){return new Map();}},['lost']),/缺少响应项/);});
test('repository list works under strict KV contract and retains the record',async t=>{const f=await fresh(t);config(f);await seed(f,{id:'x',name:'Saved',expiryDate:'2030-01-01',isActive:true,customType:'开会员'},null);const rows=await getAllSubscriptions(f.env);assert.equal(rows.length,1);assert.equal(rows[0].name,'Saved');});
test('backup API works under strict KV and does not leak configured passwords',async t=>{const f=await fresh(t);config(f);await seed(f,{id:'x',name:'Saved',expiryDate:'2030-01-01',isActive:true,customType:'开会员'},null);const r=await api(f,'GET','/api/backup');assert.equal(r.res.status,200,JSON.stringify(r.body));assert.equal(r.body.subscriptions.length,1);assert.equal(r.body.config.ADMIN_PASSWORD,undefined);});
test('create syncs legacy category and Database menu, with no dropped subscription',async t=>{const f=await fresh(t);config(f);const r=await acceptSubscriptionRecord(incoming,f.env,{operationId:'create'});assert.equal(r.success,true,r.message);assert.ok((await getCategories(f.env)).includes('流媒体'));assert.ok((await getMenuOptions(f.env)).categories.includes('流媒体'));assert.ok(f.values.has('sub:'+r.subscription.id));});
test('non-membership also records category without creating a current membership',async t=>{const f=await fresh(t);config(f);const r=await acceptSubscriptionRecord({...incoming,customType:'充积分'},f.env,{operationId:'history'});assert.equal(r.success,true,r.message);assert.equal(r.historyOnly,true);assert.ok((await getCategories(f.env)).includes('流媒体'));assert.equal((await getAllSubscriptions(f.env)).length,0);});
test('invalid input does not create category entries before validation',async t=>{const f=await fresh(t);config(f);const r=await acceptSubscriptionRecord({...incoming,name:''},f.env,{operationId:'invalid'});assert.equal(r.success,false);assert.deepEqual(await getCategories(f.env),[]);});
test('category mirror failure reports warning while preserving successful committed operation',async t=>{const f=await fresh(t);config(f);const put=f.env.SUBSCRIPTIONS_KV.put;f.env.SUBSCRIPTIONS_KV.put=async(k,v,...o)=>{if(k==='categories')throw new Error('injected category failure');return put(k,v,...o);};const r=await acceptSubscriptionRecord(incoming,f.env,{operationId:'partial'});assert.equal(r.success,true);assert.equal(r.metadataWarnings.length,1);f.env.SUBSCRIPTIONS_KV.put=put;const again=await acceptSubscriptionRecord(incoming,f.env,{operationId:'partial'});assert.equal(again.replayed,true);assert.deepEqual(again.metadataWarnings,[]);assert.ok((await getCategories(f.env)).includes('流媒体'));assert.equal([...f.values.keys()].filter(k=>k==='subscription_ledger:partial').length,1);});
test('replay cannot add another receipt or reset current subscription dates',async t=>{const f=await fresh(t);config(f);const a=await acceptSubscriptionRecord(incoming,f.env,{operationId:'replay'});assert.equal(a.success,true);const before=f.values.get('sub:'+a.subscription.id);await acceptSubscriptionRecord(incoming,f.env,{operationId:'replay'});assert.equal(f.values.get('sub:'+a.subscription.id),before);assert.equal((await getCategories(f.env)).filter(s=>s==='流媒体').length,1);});
test('D1-backed category/menu sync survives independent API calls',async t=>{const f=await fresh(t,{d1:true});config(f);const r=await api(f,'POST','/api/subscriptions',{...incoming,operationId:'d1-category'});assert.equal(r.body.success,true,JSON.stringify(r.body));const c=await api(f,'GET','/api/categories');assert.ok(c.body.categories.includes('流媒体'));const row=f.db.prepare("SELECT value FROM menu_options WHERE group_key='categories' AND value=?").get('流媒体');assert.equal(row.value,'流媒体');});

test('runtime SuperAdmin compatibility functions are exported',()=>{assert.equal(typeof superadmin.getRuntimeSuperAdminCredentials,'function');assert.equal(typeof superadmin.verifyRuntimeSuperAdminCredentials,'function');});
test('runtime credentials require both fields; no hardcoded/config fallback',()=>{const get=superadmin.getRuntimeSuperAdminCredentials;assert.equal(get({}),null);assert.equal(get({SUBSTRACKER_SUPERADMIN_PASSWORD:'secret'}),null);assert.equal(get({SUBSTRACKER_SUPERADMIN_USERNAME:'root'}),null);assert.equal(get({SUBSTRACKER_SUPERADMIN_USERNAME:' ',SUBSTRACKER_SUPERADMIN_PASSWORD:'secret'}),null);assert.deepEqual(get({SUBSTRACKER_SUPERADMIN_USERNAME:'root-admin',SUBSTRACKER_SUPERADMIN_PASSWORD:'second-secret'}),{username:'root-admin',password:'second-secret'});});
test('runtime verifier checks both username and password, including empty/nonstring inputs',async()=>{const env={SUBSTRACKER_SUPERADMIN_USERNAME:'root-admin',SUBSTRACKER_SUPERADMIN_PASSWORD:'second-secret'};const verify=superadmin.verifyRuntimeSuperAdminCredentials;assert.equal(await verify(env,'root-admin','second-secret'),true);for(const [u,p] of [['other','second-secret'],['root-admin','wrong'],['',''],[null,'second-secret'],['root-admin',1]])assert.equal(await verify(env,u,p),false);});
test('password whitespace is preserved, not silently trimmed',async()=>{const env={SUBSTRACKER_SUPERADMIN_USERNAME:'root',SUBSTRACKER_SUPERADMIN_PASSWORD:' secret '};assert.equal(await superadmin.verifyRuntimeSuperAdminCredentials(env,'root',' secret '),true);assert.equal(await superadmin.verifyRuntimeSuperAdminCredentials(env,'root','secret'),false);});
async function login(f,user,password){return handleApiRequest(new Request('https://local.invalid/api/login',{method:'POST',headers:{'Content-Type':'application/json','CF-Connecting-IP':'127.0.0.1'},body:JSON.stringify({username:user,password})}),f.env);}
test('independent runtime SuperAdmin login gets proper role and HttpOnly cookies',async t=>{const f=await fresh(t);const cfg=config(f);Object.assign(f.env,{SUBSTRACKER_SUPERADMIN_USERNAME:'root-admin',SUBSTRACKER_SUPERADMIN_PASSWORD:'second-secret'});const r=await login(f,'root-admin','second-secret');const b=await r.json();assert.equal(b.success,true,JSON.stringify(b));assert.equal(b.superAdmin,true);const cookies=r.headers.get('set-cookie');assert.match(cookies,/superadmin_token=/);assert.match(cookies,/HttpOnly/);const token=cookies.match(/(?:^|,\s*)token=([^;]+)/)[1];assert.equal((await verifyJWT(token,cfg.JWT_SECRET)).role,'superadmin');});
test('explicit runtime username does not accept admin-name plus elevated password',async t=>{const f=await fresh(t);config(f);Object.assign(f.env,{SUBSTRACKER_SUPERADMIN_USERNAME:'root-admin',SUBSTRACKER_SUPERADMIN_PASSWORD:'second-secret'});assert.equal((await (await login(f,'admin','second-secret')).json()).success,false);});
test('ordinary admin login remains valid and clears elevated cookie',async t=>{const f=await fresh(t);config(f);Object.assign(f.env,{SUBSTRACKER_SUPERADMIN_USERNAME:'root-admin',SUBSTRACKER_SUPERADMIN_PASSWORD:'second-secret'});const r=await login(f,'admin','ordinary-secret');assert.deepEqual(await r.json(),{success:true,superAdmin:false});assert.match(r.headers.get('set-cookie'),/superadmin_token=;.*Max-Age=0/);});
test('password-only legacy SuperAdmin flow is preserved when username is not configured',async t=>{const f=await fresh(t);config(f);f.env.SUBSTRACKER_SUPERADMIN_PASSWORD='old-second-secret';assert.equal((await (await login(f,'admin','old-second-secret')).json()).superAdmin,true);assert.equal(await superadmin.verifySuperAdminPassword('old-second-secret',f.env),true);});
test('explicit empty independent username fails closed without breaking ordinary admin',async t=>{const f=await fresh(t);config(f);Object.assign(f.env,{SUBSTRACKER_SUPERADMIN_USERNAME:'',SUBSTRACKER_SUPERADMIN_PASSWORD:'second-secret'});assert.equal((await (await login(f,'admin','second-secret')).json()).success,false);assert.equal((await (await login(f,'admin','ordinary-secret')).json()).success,true);});

test('scheduler: correct timezone sends a day-rule notification with strict KV reads',async t=>{freeze(t,'2026-05-24T00:00:00Z');const f=await fresh(t);config(f,{TIMEZONE:'Asia/Shanghai',NOTIFICATION_HOURS:['08']});const count=mockChannel(t);await seed(f,{id:'day',name:'Day',isActive:true,autoRenew:false,expiryDate:'2026-05-31T03:00:00Z',reminderUnit:'day',reminderValue:7},{id:'r7',type:'before_expiry',value:7,unit:'days'});const r=await checkExpiringSubscriptions(f.env);assert.equal(r.status,'ok',r.reason);assert.equal(r.sentCount,1);assert.equal(r.matchedCount,1);assert.equal(count(),1);});
test('scheduler: outside the window skips without a KV exception',async t=>{freeze(t,'2026-05-24T00:00:00Z');const f=await fresh(t);config(f,{TIMEZONE:'Asia/Shanghai',NOTIFICATION_HOURS:['00']});const count=mockChannel(t);await seed(f,{id:'day',name:'Day',isActive:true,autoRenew:false,expiryDate:'2026-05-31T03:00:00Z'},null);const r=await checkExpiringSubscriptions(f.env);assert.equal(r.status,'skipped',r.reason);assert.equal(count(),0);});
test('scheduler: daily dedupe works across two hours on the same date',async t=>{const clock=freeze(t,'2026-06-01T08:00:00Z');const f=await fresh(t);config(f);mockChannel(t);await seed(f,{id:'day',name:'Day',isActive:true,autoRenew:false,expiryDate:'2026-06-08T00:00:00Z'},{id:'r7',type:'before_expiry',value:7,unit:'days'});assert.equal((await checkExpiringSubscriptions(f.env)).sentCount,1);clock('2026-06-01T20:00:00Z');const next=await checkExpiringSubscriptions(f.env);assert.equal(next.sentCount,0);assert.equal(next.dedupedCount,1);});
test('scheduler: failed delivery does not reserve dedupe; retry can send',async t=>{freeze(t,'2026-06-01T08:00:00Z');const f=await fresh(t);config(f);mockChannel(t,{failFirst:true});await seed(f,{id:'day',name:'Day',isActive:true,autoRenew:false,expiryDate:'2026-06-08T00:00:00Z'},{id:'r7',type:'before_expiry',value:7,unit:'days'});assert.equal((await checkExpiringSubscriptions(f.env)).sentCount,0);assert.equal((await checkExpiringSubscriptions(f.env)).sentCount,1);});
test('scheduler: reset + renewal off stays expired and observes after-expiry interval',async t=>{const clock=freeze(t,'2026-06-10T08:00:00Z');const f=await fresh(t);config(f);mockChannel(t);await seed(f,{id:'expired',name:'Expired',subscriptionMode:'reset',isActive:true,autoRenew:false,periodValue:1,periodUnit:'month',expiryDate:'2026-06-01T00:00:00Z'},{id:'after',type:'after_expiry',value:0,unit:'days',repeatInterval:24});assert.equal((await checkExpiringSubscriptions(f.env)).sentCount,1);clock('2026-06-10T10:00:00Z');assert.equal((await checkExpiringSubscriptions(f.env)).sentCount,0);const sub=JSON.parse(f.values.get('sub:expired'));assert.equal(sub.expiryDate,'2026-06-01T00:00:00Z');assert.equal(sub.memberLevel,'Free');});
test('scheduler: cycle + renewal off still advances dates but invents no payment',async t=>{freeze(t,'2026-06-10T08:00:00Z');const f=await fresh(t);config(f);mockChannel(t);await seed(f,{id:'cycle',name:'Cycle',subscriptionMode:'cycle',isActive:true,autoRenew:false,periodValue:1,periodUnit:'month',startDate:'2026-05-01T00:00:00Z',expiryDate:'2026-06-01T00:00:00Z',paymentHistory:[]},{id:'after',type:'after_expiry',value:0,unit:'days',repeatInterval:24});const r=await checkExpiringSubscriptions(f.env);assert.equal(r.autoRenewedCount,1,r.reason);assert.equal(r.sentCount,0);const sub=JSON.parse(f.values.get('sub:cycle'));assert.ok(Date.parse(sub.expiryDate)>Date.now());assert.equal(sub.paymentHistory.length,0);});
test('scheduler: cycle renewal appends history once, not on every tick',async t=>{freeze(t,'2026-06-10T08:00:00Z');const f=await fresh(t);config(f);mockChannel(t);await seed(f,{id:'renew',name:'Renew',customType:'开会员',subscriptionMode:'cycle',isActive:true,autoRenew:true,periodValue:1,periodUnit:'month',startDate:'2026-05-01T00:00:00Z',expiryDate:'2026-06-01T00:00:00Z',amount:5,currency:'CNY',paymentHistory:[]},null);const r=await checkExpiringSubscriptions(f.env);assert.equal(r.autoRenewedCount,1,r.reason);const raw=f.values.get('sub:renew');const paymentCount=JSON.parse(raw).paymentHistory.length;assert.ok(paymentCount>=1);const again=await checkExpiringSubscriptions(f.env);assert.equal(again.autoRenewedCount,0);assert.equal(JSON.parse(f.values.get('sub:renew')).paymentHistory.length,paymentCount);});
