import test from 'node:test';import assert from 'node:assert/strict';
import {assertSameBaseline} from '../../scripts/upgrade/split-baseline.mjs';
import {CloudflareCheckpoints,checkpointPrefixes} from '../../scripts/upgrade/cloudflare-checkpoints.mjs';
import {DatabaseSync} from 'node:sqlite';
const prefix=checkpointPrefixes('a'.repeat(32),'worker').control;
function fixture(){const image={schema_meta:{columns:['key','value'],rows:[{key:'keep',value:'exact'}]},accounts:{columns:['id'],rows:[{id:'a'}]}};return {summary:{kvDigest:'same-kv',sqlDigest:'same-sql',sourceDigest:'same-source'},image};}
test('append-only split metadata does not invalidate maintenance backup',()=>{const before=fixture(),after=structuredClone(before);after.image.schema_meta.rows.push({key:prefix+'checkpoint:new',value:'new'});after.summary.sqlDigest='new-sql';assert.doesNotThrow(()=>assertSameBaseline({kv:[]},{kv:[]},before,after,prefix));});
test('changed original metadata cannot hide behind the operational prefix filter',()=>{const before=fixture();before.image.schema_meta.rows.push({key:prefix+'lease:old',value:'old'});const after=structuredClone(before);after.image.schema_meta.rows[1].value='changed';assert.throws(()=>assertSameBaseline({kv:[]},{kv:[]},before,after,prefix),/原始记录保护/);});
test('new ordinary metadata must not be silently accepted as checkpoint bookkeeping',()=>{const before=fixture(),after=structuredClone(before);after.image.schema_meta.rows.push({key:'setting:replacement',value:'new'});assert.throws(()=>assertSameBaseline({kv:[]},{kv:[]},before,after,prefix),/业务 SQL/);});
test('source changes stop, even if summary row counts are identical',()=>{const before=fixture(),after=structuredClone(before);after.summary.sourceDigest='different';assert.throws(()=>assertSameBaseline({kv:[]},{kv:[]},before,after,prefix),/订阅来源/);});
test('KV-only is not silently given a race-prone deployment lease',()=>{assert.throws(()=>new CloudflareCheckpoints({accountId:'a'.repeat(32)},{worker:'w',bindings:{kvId:'b'.repeat(32)},password:'long-enough-password'}),/ST_SPLIT_D1_REQUIRED/);});
async function stores(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE schema_meta(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT)');const cf={accountId:'a'.repeat(32),async request(url,{body}){const results=db.prepare(body.sql).all(...body.params);return {result:[{success:true,results}]};}};const opts={worker:'w',bindings:{kvId:'b'.repeat(32),dbId:'synthetic'},password:'long-enough-password'};return {db,a:new CloudflareCheckpoints(cf,opts),b:new CloudflareCheckpoints(cf,opts)};}
test('D1 lease insertion atomically excludes a concurrent Build; release is append-only',async()=>{const {db,a,b}=await stores();try{await a.acquire();await assert.rejects(b.acquire(),/ST_SPLIT_BUSY/);await a.assertLease();const original=db.prepare('SELECT * FROM schema_meta').all()[0];await a.release();assert.deepEqual(db.prepare('SELECT * FROM schema_meta WHERE key=?').get(original.key),original);await b.acquire();await b.assertLease();}finally{db.close();}});
test('expired lease can be superseded without deleting the original claim',async()=>{const {db,a,b}=await stores();try{await a.acquire();const old=db.prepare('SELECT * FROM schema_meta').all()[0];const json=JSON.parse(old.value);json.expiresAt=Date.now()-1;db.prepare('UPDATE schema_meta SET value=? WHERE key=?').run(JSON.stringify(json),old.key);await b.acquire();await assert.rejects(a.assertLease(),/ST_SPLIT_LEASE_EXPIRED/);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM schema_meta').get().n,2);}finally{db.close();}});
